### ISSUE TITLE
when I use the mod with a texturepack the glass pane is bugged and still shows the buttom layers.

### ISSUE THREAD

**Issue by TheNukeLore** [PepperCode1/ConnectedTexturesMod-Fabric#1] opened 2021-02-03 01:43 UTC

**Comment by PepperCode1** [comment] 2021-02-03 05:21
Could you provide the resource pack zip or link? This seems like intended behavior because vanilla glass pane models do not cull top and bottom faces.

**Comment by PepperCode1** [comment] 2021-02-12 03:14
I'm closing this issue as the author seemed to have confirmed that there was a misunderstanding and there is actually no bug. If there is a bug, please open another issue.

**Closed as completed by PepperCode1** 2021-02-12 03:14 UTC
