### ISSUE TITLE
Client can't start with CTM

### ISSUE THREAD

**Issue by ghost** [PepperCode1/ConnectedTexturesMod-Fabric#22] opened 2021-06-27 20:38 UTC
[2021-06-27-2.log](https://github.com/PepperCode1/ConnectedTexturesMod-Fabric/files/6722272/2021-06-27-2.log)

Newest Fabric Version
Minecraft 1.16.5
Newest CTM Version
Modlist: http://game.mineasia.de/downloads/mineasia-alpha/MineAsia-Alpha.xml

**Comment by PepperCode1** [comment] 2021-07-04 03:37
A ConcurrentModificationException is quite unexpected here, because the operations inside of the loop never modify the map. This could be an incompatibility with another mod that modifies the same map on a different thread.

**Comment by Mysticpasta1** [comment] 2021-07-06 11:46
[06:32:12] [main/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.6) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_242]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_242]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_242]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_242]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_242]
	at team.chisel.ctm.client.handler.CTMModelsAddedCallbackHandler.onModelsAdded(CTMModelsAddedCallbackHandler.java:38) ~[ctm-fabric-0.4.0.jar:?]
	at team.chisel.ctm.client.event.ModelsAddedCallback.lambda$static$0(ModelsAddedCallback.java:18) ~[ctm-fabric-0.4.0.jar:?]
	at net.minecraft.client.render.model.ModelLoader.handler$cbc000$onFinishAddingModels(ModelLoader:2612) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.<init>(ModelLoader:213) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.prepare(BakedModelManager:52) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.prepare(BakedModelManager:19) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloadListener.method_18791(SinglePreparationResourceReloadListener:11) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_242]
	... 5 more
	
This is from part of a log where the bug starts, it does show this any other time and remove CTM does fix it 
A picture to shows what happened with it.
![ctm crash](https://user-images.githubusercontent.com/45608372/124594774-d2662d80-de25-11eb-85a0-f0b27e2a0724.png)

**Comment by Mysticpasta1** [comment] 2021-07-06 11:46
It seems to be the same type of bug btw.

**Comment by Angular-Angel** [comment] 2021-07-17 19:58
Yeah I'm getting the same thing. I have a ton of mods, so it's probably a mod interaction.

`[13:56:55] [Render thread/INFO]: Reloading ResourceManager: Default, Runtime Resource Packebe:pack, Fabric Mods (Fabric Key Bindings (v0), Trinkets, Fabric Loader, MoreVillagersFabric, Hydrogen, Beenfo, Fabric Dimensions API (v1), Fabric Game Rule API (v1), Fabric API Base, ConnectedTexturesMod for Fabric, LambDynamicLights, Elytra Trinket, Concurrent Chunk Management Engine, Fabric BlockRenderLayer Registration (v1), Promenade, Fabric API, BCLib, Dawn API, Fabric Networking (v0), Scorch, Immersive Portals Core, Fabric API Lookup API (v1), Fabric Screen Handler API (v1), Repurposed Structures, Fabric Tool Attribute API (v1), Simply Improved Terrain, Culinaire, Blockus, Fabric Crash Report Info (v1), Fabric Events Interaction (v0), wthit, Mo' Structures, Fabric Language Kotlin, Enchantment Descriptions, Artisanat, Fabric Key Binding API (v1), Better Biome Blend, Cloth Config v4, Fabric Resource Loader (v0), YUNG's Better Strongholds, Smoke Suppression, Enhanced Block Entities, Fabric Registry Sync (v0), Fabric Commands (v0), Adorn, VanillaEnhanced, Fabric Mining Levels (v0), Fabric Networking API (v1), Krypton, Charm, Fabric Item Groups (v0), Fabric Models (v0), Vein Mining, True Secret Rooms, Terraform Shapes API (v1), Fabric Renderer API (v1), GBfabrictools, LibCapableData, Better Withered Mobs, Fabric Structure API (v1), Lithium, Fabric Containers (v0), Fabric Object Builder API (v1), Caelus API, Vanilla Plus Biomes, Waystones, Axolotl Item Fix, Comforts, Fabric Rendering Data Attachment (v1), Stoneholm, Fabric Textures (v0), Snow Under Trees, XP Storage, Fabric Rendering Fluids (v1), LazyDFU, Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Immersive Portals, Fabric Loot Tables (v1), Dynamic FPS, Fabric Particles (v1), Artifality, No Fade, Fabric Networking Block Entity (v0), Jankson, Fabric Command API (v1), Universal Ores, Animal Feeding Trough, Concrete Conversion, Fabric Screen API (v1), Fabric Renderer - Indigo, Fiber To Cloth, Roughly Enough Items, Fabric Item API (v1), LibGui, Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Rendering (v1), SpruceUI, Auto Config v1 Updated, EntityCulling-Fabric, Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Runtime Resource Pack, AppleSkin, Ring Of Attraction, Lakeside, Fabric Events Lifecycle (v0), Fabric Tree Chopper, Flight Rings, Better End, Fabric Object Builders (v0), Magic Mirror)
[13:56:55] [Render thread/INFO]: closing rrp ebe:pack
[13:56:55] [Render thread/INFO]: ARRP register - before vanilla
[13:56:55] [Render thread/INFO]: [STDOUT]: Inject generated resource packs.
[13:56:55] [Render thread/INFO]: ARRP register - after vanilla
[13:57:00] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1584) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1617) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1615) ~[?:?]
	at team.chisel.ctm.client.handler.CTMModelsAddedCallbackHandler.onModelsAdded(CTMModelsAddedCallbackHandler.java:39) ~[ctm-fabric-0.5.0+1.17.jar:?]
	at team.chisel.ctm.client.event.ModelsAddedCallback.lambda$static$0(ModelsAddedCallback.java:18) ~[ctm-fabric-0.5.0+1.17.jar:?]
	at net.minecraft.class_1088.handler$bjn000$onFinishAddingModels(class_1088.java:2616) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1088.<init>(class_1088.java:217) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1092.method_18178(class_1092.java:52) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1092.method_18789(class_1092.java:19) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
	... 6 more`

**Comment by Zuramo** [comment] 2021-07-25 17:55
Not really a dev, but I managed to trace the issue to an incompatibility with BetterEnds after hours of turning off mods; although I'm on 1.17.1, here's the error:

`[10:54:09] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.29) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1584) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1617) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1615) ~[?:?]
	at team.chisel.ctm.client.handler.CTMModelsAddedCallbackHandler.onModelsAdded(CTMModelsAddedCallbackHandler.java:39) ~[ctm-fabric-0.5.0+1.17%20(2).jar:?]
	at team.chisel.ctm.client.event.ModelsAddedCallback.lambda$static$0(ModelsAddedCallback.java:18) ~[ctm-fabric-0.5.0+1.17%20(2).jar:?]
	at net.minecraft.client.render.model.ModelLoader.handler$bom000$onFinishAddingModels(ModelLoader:2616) ~[?:?]
	at net.minecraft.client.render.model.ModelLoader.<init>(ModelLoader:217) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.prepare(BakedModelManager:52) ~[?:?]
	at net.minecraft.client.render.model.BakedModelManager.prepare(BakedModelManager:19) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18791(SinglePreparationResourceReloader:11) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
	... 6 more`

**Comment by PepperCode1** [comment] 2021-07-25 17:59
I've talked with the BetterEnd dev and they said they will make a fix but that it might take a while, so it will be fixed eventually.

**Closed as completed** 2021-08-06 23:44 UTC
Labels: bug

**Comment by PepperCode1** [comment] 2021-08-07 00:33
Note that while 0.5.1 fixes the resource reload loop with BetterEnd present, some of BetterEnd's block models, like for ladders and doors, appear as missing. This will be fixed by the next BetterEnd update.
